sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install tornado esptool flake8==3.5.0 pylint==1.8.4
script:
 - flake8 esphomeyaml
 - pylint esphomeyaml
