esphomeyaml:
  name: lebensmittelkeller
  platform: ESP8266
  board: nodemcuv2

logger:
  level: verbose

wifi:
  ssid: '[SSID]'
  password: '[PASSWORD]'
  manual_ip:
    static_ip: 192.168.178.209
    gateway: 192.168.178.1
    subnet: 255.255.255.0

ota:

mqtt:
  broker: 192.168.178.84
  username: lebensmittelkeller
  password: '[PASSWORD]'
  # This is the default
  discovery: true

sensor:
  - platform: dht
    pin: D3
    temperature:
      name: 'Lebensmittelkeller Temperatur'
    humidity:
      name: 'Lebensmittelkeller Feuchtigkeit'
    model: DHT22
  - platform: adc
    pin: A0
    name: "Lebensmittelkeller Helligkeit"

output:
  - platform: gpio
    pin: D4
    id: 'ventilator'

fan:
  - platform: binary
    output: 'ventilator'
    name: 'Lebensmittelkeller Ventilator'

switch:
  - platform: gpio
    pin: D2
    name: 'Lebensmittelkeller Entfeuchter'
    icon: 'mdi:water-off'
  - platform: restart
    name: "Lebensmittelkeller Neustart"

binary_sensor:
  - platform: status
    name: "Lebensmittelkeller Status"
