esphomeyaml:
  name: livingroom
  platform: ESP32
  board: nodemcu-32s

logger:
  level: verbose

wifi:
  ssid: '[SSID]'
  password: '[PASSWORD]'
  manual_ip:
    static_ip: 192.168.178.201
    gateway: 192.168.178.1
    subnet: 255.255.255.0

ota:

mqtt:
  broker: 192.168.178.84
  username: livingroom
  password: '[PASSWORD]'
  # This is the default
  discovery: true

output:
  - platform: ledc
    id: 'fan_float'
    frequency: 50000
    pin: 22
    bit_depth: 8

dallas:
  pin: 23
  id: dallas

sensor:
  - platform: dallas
    dallas_id: dallas
    address: 0x1c0000031edd2a28
    name: "Wohnzimmer Raumtemperatur"
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
      - filter_out: 85
  - platform: dallas
    dallas_id: dallas
    address: 0x7a0315a8371eff28
    name: "Wohnzimmer Heizkörpertemperatur"
    update_interval: 30s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
      - filter_out: 85

fan:
  - platform: speed
    output: 'fan_float'
    name: 'Wohnzimmer Heizkörper Ventilator'

binary_sensor:
  - platform: status
    name: "Wohnzimmer Status"

ir_transmitter:
  pin: 32
  id: 'ir'

switch:
  - platform: restart
    name: "Wohnzimmer Neustart"
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV On"
    panasonic:
      address: 0x4004
      command: 0x100BCBD
    repeat: 25
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Off"
    panasonic:
      address: 0x4004
      command: 0x100BCBD
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV SD Card"
    panasonic:
      address: 0x4004
      command: 0x190D544
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Input TV"
    panasonic:
      address: 0x4004
      command: 0x1400C4D
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Input AV"
    panasonic:
      address: 0x4004
      command: 0x100A0A1
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Menu"
    panasonic:
      address: 0x4004
      command: 0x1004A4B
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Aspect Ratio"
    panasonic:
      address: 0x4004
      command: 0x1207B5A
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Viera Cast"
    panasonic:
      address: 0x4004
      command: 0x190C958
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Direct TV REC"
    panasonic:
      address: 0x4004
      command: 0x1909100
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Info"
    panasonic:
      address: 0x4004
      command: 0x1009C9D
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Exit"
    panasonic:
      address: 0x4004
      command: 0x100CBCA
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Viera Link"
    panasonic:
      address: 0x4004
      command: 0x1908D1C
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Viera Tools"
    panasonic:
      address: 0x4004
      command: 0x100F7F6
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Guide"
    panasonic:
      address: 0x4004
      command: 0x190E170
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Up"
    panasonic:
      address: 0x4004
      command: 0x1005253
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Left"
    panasonic:
      address: 0x4004
      command: 0x1007273
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV OK"
    panasonic:
      address: 0x4004
      command: 0x1009293
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Right"
    panasonic:
      address: 0x4004
      command: 0x100F2F3
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Down"
    panasonic:
      address: 0x4004
      command: 0x100D2D3
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Option"
    panasonic:
      address: 0x4004
      command: 0x190E574
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Back"
    panasonic:
      address: 0x4004
      command: 0x1002B2A
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Red"
    panasonic:
      address: 0x4004
      command: 0x1000E0F
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Green"
    panasonic:
      address: 0x4004
      command: 0x1000E0F  # TODO: FIXME
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Yellow"
    panasonic:
      address: 0x4004
      command: 0x1004E4F
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Blue"
    panasonic:
      address: 0x4004
      command: 0x100CECF
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Text"
    panasonic:
      address: 0x4004
      command: 0x180C041
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Subtitle"
    panasonic:
      address: 0x4004
      command: 0x180A021
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Index"
    panasonic:
      address: 0x4004
      command: 0x1801091
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Hold"
    panasonic:
      address: 0x4004
      command: 0x1809011
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 1"
    panasonic:
      address: 0x4004
      command: 0x1000809
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 2"
    panasonic:
      address: 0x4004
      command: 0x1008889
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 3"
    panasonic:
      address: 0x4004
      command: 0x1004849
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 4"
    panasonic:
      address: 0x4004
      command: 0x100C8C9
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 5"
    panasonic:
      address: 0x4004
      command: 0x1002829
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 6"
    panasonic:
      address: 0x4004
      command: 0x100A8A9
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 7"
    panasonic:
      address: 0x4004
      command: 0x1006869
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 8"
    panasonic:
      address: 0x4004
      command: 0x100E8E9
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 9"
    panasonic:
      address: 0x4004
      command: 0x1001819
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV 0"
    panasonic:
      address: 0x4004
      command: 0x1009899
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Mute"
    panasonic:
      address: 0x4004
      command: 0x1004C4D
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Last View"
    panasonic:
      address: 0x4004
      command: 0x100ECED
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Volume Up"
    panasonic:
      address: 0x4004
      command: 0x1000405
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Volume Down"
    panasonic:
      address: 0x4004
      command: 0x1008485
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Program Up"
    panasonic:
      address: 0x4004
      command: 0x1002C2D
  - platform: ir_transmitter
    ir_transmitter_id: 'ir'
    name: "Panasonic TV Program Down"
    panasonic:
      address: 0x4004
      command: 0x100ACAD
