esphomeyaml:
  name: terrasse
  platform: ESP32
  board: nodemcu-32s

logger:
  level: verbose

wifi:
  ssid: '[SSID]'
  password: '[PASSWORD]'
  manual_ip:
    static_ip: 192.168.178.205
    gateway: 192.168.178.1
    subnet: 255.255.255.0

ota:

mqtt:
  broker: 192.168.178.84
  username: terrasse
  password: '[PASSWORD]'
  # This is the default
  discovery: true

dallas:
  pin: 25
  id: dallas

sensor:
  - platform: pulse_counter
    pin: 34
    name: "Terrasse Wind"
  - platform: pulse_counter
    pin: 39
    name: "Terrasse Regen"
  - platform: dallas
    dallas_id: dallas
    index: 0
    name: "Terrasse Temperatur"

binary_sensor:
  - platform: status
    name: "Terrasse Status"

switch:
  - platform: restart
    name: "Terrasse Neustart"
